name: Build and publish wheels

on:
  push:
    branches:
      - main  # Change this to the main branch name, or use 'master' if that's the default branch.

jobs:
  build:
    name: Build wheel for ${{ matrix.python }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      matrix:
        # Github Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
          # - [ubuntu-20.04, manylinux_x86_64]
          # - [ubuntu-20.04, musllinux_x86_64]
          - [macos-12, macosx_x86_64]
          - [windows-2019, win_amd64]
          # - [windows-2019, win32]
        python: ["cp311"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    
    - name: Build wheels
      uses: pypa/cibuildwheel@7da7df1efc530f07d1945c00934b8cfd34be0d50 # v2.16.1
      env:
        CIBW_PRERELEASE_PYTHONS: True
        CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}

    - uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
      with:
        name: ${{ matrix.python }}-${{ startsWith(matrix.buildplat[1], 'macosx') && 'macosx' || matrix.buildplat[1] }}
        path: ./wheelhouse/*.whl

    - name: Install Twine
      run: python -m pip install twine

    - name: Publish to PyPI
      if: github.event_name == 'push'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload wheelhouse/*