name: Build and publish wheels

on:
  push:
    branches:
      - main  # Change this to the main branch name, or use 'master' if that's the default branch.

      jobs:
        build:
          runs-on: ubuntu-latest
          strategy:
            matrix:
              python-version: [3.11]
            
          steps:
          - uses: actions/checkout@v2
      
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
              python-version: ${{ matrix.python-version }}
          
          - name: Install cibuildwheel
            run: python -m pip install cibuildwheel
          - name: Build wheels
            run: python -m cibuildwheel --output-dir wheelhouse
          - name: Publish wheels to PyPI
            uses: pypa/gh-action-pypi-publish@v1.4.2
            with:
              user: __token__
              password: ${{ secrets.PYPI_API_TOKEN }}
              packages_dir: wheelhouse

